package ER.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Cardinality extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Cardinality() {
    super(0x4242f2260ea540a5L, 0x90c79b2c0255ebbaL, 0x5271510262a59b79L, "Cardinality", "r:4d526599-4195-4f7a-a1be-f5a7d3bb5f9b(ER.structure)/5940618454165199737");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_One_One_0 = new EnumerationDescriptor.MemberDescriptor("One_One", "1:1", 0x5271510262a59b7aL, "r:4d526599-4195-4f7a-a1be-f5a7d3bb5f9b(ER.structure)/5940618454165199738");
  private final EnumerationDescriptor.MemberDescriptor myMember_One_Many_0 = new EnumerationDescriptor.MemberDescriptor("One_Many", "1:n", 0x5271510262a59b82L, "r:4d526599-4195-4f7a-a1be-f5a7d3bb5f9b(ER.structure)/5940618454165199746");
  private final EnumerationDescriptor.MemberDescriptor myMember_Many_One_0 = new EnumerationDescriptor.MemberDescriptor("Many_One", "n:1", 0x5271510262a59b87L, "r:4d526599-4195-4f7a-a1be-f5a7d3bb5f9b(ER.structure)/5940618454165199751");
  private final EnumerationDescriptor.MemberDescriptor myMember_Many_Many_0 = new EnumerationDescriptor.MemberDescriptor("Many_Many", "n:n", 0x5271510262a59b8eL, "r:4d526599-4195-4f7a-a1be-f5a7d3bb5f9b(ER.structure)/5940618454165199758");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x4242f2260ea540a5L, 0x90c79b2c0255ebbaL, 0x5271510262a59b79L, 0x5271510262a59b7aL, 0x5271510262a59b82L, 0x5271510262a59b87L, 0x5271510262a59b8eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_One_One_0, myMember_One_Many_0, myMember_Many_One_0, myMember_Many_Many_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "One_One":
        return myMember_One_One_0;
      case "One_Many":
        return myMember_One_Many_0;
      case "Many_One":
        return myMember_Many_One_0;
      case "Many_Many":
        return myMember_Many_Many_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
