package ER.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Attribute = 0;
  public static final int Database = 1;
  public static final int Entity = 2;
  public static final int Relation = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4242f2260ea540a5L, 0x90c79b2c0255ebbaL);
    builder.put(0x7d5ac9d86a0d8bafL, Attribute);
    builder.put(0x7d5ac9d86a0d8bd3L, Database);
    builder.put(0x7d5ac9d86a0d8baaL, Entity);
    builder.put(0x7d5ac9d86a0d8bbdL, Relation);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
